config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  root to:"posts#home"
  get 'posts/home'
  devise_for :users
  get "/new", to:"posts#new"
  post "/create", to:"posts#create"
  get "/users/sign_out", to:"tweets#logout"
  get "/users/:id", to:"users#user_page"
  delete "/posts/:id", to:"users#destroy"
  get "/posts/:id", to:"posts#show"

  resources :users
  resources :posts, only: [:index, :show, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
    validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        posts_home_path
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    #投稿に紐づいたコメントを作成
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    render :index
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    render :index
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

    def home
        @posts = Post.all.order(created_at: :desc)
    end

    def show
        @post = Post.find(params[:id])
        @comment = Comment.new
        @comments = @post.comments.order(created_at: :desc)
      end

    def new
        
    end

    def create
        Post.create(body:params["posts"]["body"], user_id:current_user.id)
        redirect_to "/"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def user_page
      @posts = Post.where(user_id: current_user.id).all.order(created_at: :desc)
    end
  
    def destroy
      post = Post.find(params["id"])
      post.destroy
      redirect_to controller: "users", action: "user_page"
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<!-- コメント入力フォーム ------------------------------------------------------------>
<%= form_with(model: [post, comment], url: post_comments_path(@post) ) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class:"form-control", :size => "10x5", placeholder:"Your Comment" %>
  </div>
    <%= f.submit "Comment", class: "btn btn-outline-dark comment-submit float-right" %>
<% end %>

app/views/comments/_index.html.erb
<!-- コメント内容(２件) ------------------------------------------------------------------>
<%= comments.count %> comments
<h5 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">read more....</h5>
<% comments.first(2).each do |comment| %>
  <% unless comment.id.nil? %>
    
        <div class="panel panel-default">
            <div class="panel-heading">
                <%= comment.user.name %>
                <div class="comment_time">
                    <%= comment.created_at.strftime('%m/%d %H:%M') %>
                </div>
            </div>
            <div class="panel-body">
                <%= comment.content %>
                <% if comment.user == current_user %>
                    <%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                        <i class="fas fa-trash" style="color: black;"></i>
                    <% end %>
                <% end %>
            </div>
        </div>
    
  <% end %>
<% end %>
<!-- コメント内容(3件目以降) ------------------------------------------------------------------>
    <div class="collapse" id="collapseExample">
            <% comments.offset(2).each do |comment| %>
              <% unless comment.id.nil? %>
              
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <%= comment.user.name %>
                            <div class="comment_time">
                                <%= comment.created_at.strftime('%m/%d %H:%M') %>
                            </div>
                        </div>
                        <div class="panel-body">
                            <%= comment.content %>
                            <% if comment.user == current_user %>
                                <%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                                    <i class="fas fa-trash" style="color: black;"></i>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
              
              <% end %>
            <% end %>
    </div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("textarea").val('')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Chat App</a>
      </div>

      <% if user_signed_in? %>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <li><a href="/"><span class="glyphicon glyphicon-home"></span></a></li>
            <li><a href="/users/<%= current_user.id %>"><span class="glyphicon glyphicon-user"></span></li><li><a href="/new"><span class="glyphicon glyphicon-pencil"></span></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <div class="logout">
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </div>
          </ul>
        </div><!-- /.navbar-collapse -->
      <% end %>
    </div><!-- /.container-fluid -->
  </nav>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/home.html.erb
<h4>Home</h4>

<% @posts.each do |post| %>
    <div class="panel panel-primary">
            <div class="panel-heading">
                <%= post.user.name %>
                <div class="post_time">
                    <%= post.created_at.strftime('%m/%d %H:%M') %>
                </div>
            </div>
            <div class="panel-body">
                <%= post.body %>
            </div>

            <div class="panel-footer">
                <div class="buttons">
                    <a href="/posts/<%=post.id%>"><span class="glyphicon glyphicon-comment"></span></a>
                </div>
            </div>
    </div>
<% end %>

app/views/posts/new.html.erb
<h4>New Post</h4>

<%= form_tag("/create") do %>
    <div class="form-group">
        <%= label_tag current_user.name%>, <%= "What's happening?" %>
        <%= text_area :posts, :body, class:"form-control", :size => "10x10" %>
    </div>
    <%= submit_tag "Post", class:"btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<div class="panel panel-primary">
    <div class="panel-heading">
        <%= @post.user.name %>
        <div class="post_time">
            <%= @post.created_at.strftime('%m/%d %H:%M') %>
        </div>
     </div>
    <div class="panel-body">
        <%= @post.body %>
    </div>
</div>

<div class="row">
    <ul>
        <li id="comments_area">
            <%= render partial: 'comments/index', locals: { comments: @comments } %>
        </li>
    </ul>
    <hr>
    <% if user_signed_in? %>
        <div class="comment-create">
            <h5 class="text-left">comment to <%= @post.user.name%>'s post</h5>
            <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
        </div>
    <% end %>
</div>

app/views/users/user_page.html.erb
<h4><%= current_user.name %>'s Tweet</h4>

<% @posts.each do |post| %>
    <div class="panel panel-primary">

            <div class="panel-heading">
                <%= post.user.name %>
                <div class="post_time">
                    <%= post.created_at.strftime('%m/%d %H:%M') %>
                </div>
            </div>
            <div class="panel-body">
                <%= post.body %>
            </div>

            <div class="panel-footer">
                <div class="buttons">
                    <a href="/posts/<%=post.id%>" data-method="delete"><span class="glyphicon glyphicon-trash"></a>
                </div>
            </div>
        
    </div>
<% end %>